/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnownRouteImport } from './routes/unown'
import { Route as ShinyRouteImport } from './routes/shiny'
import { Route as ShadowRouteImport } from './routes/shadow'
import { Route as LuckyRouteImport } from './routes/lucky'
import { Route as DexRouteImport } from './routes/dex'
import { Route as IndexRouteImport } from './routes/index'

const UnownRoute = UnownRouteImport.update({
  id: '/unown',
  path: '/unown',
  getParentRoute: () => rootRouteImport,
} as any)
const ShinyRoute = ShinyRouteImport.update({
  id: '/shiny',
  path: '/shiny',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowRoute = ShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const LuckyRoute = LuckyRouteImport.update({
  id: '/lucky',
  path: '/lucky',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dex': typeof DexRoute
  '/lucky': typeof LuckyRoute
  '/shadow': typeof ShadowRoute
  '/shiny': typeof ShinyRoute
  '/unown': typeof UnownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dex': typeof DexRoute
  '/lucky': typeof LuckyRoute
  '/shadow': typeof ShadowRoute
  '/shiny': typeof ShinyRoute
  '/unown': typeof UnownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dex': typeof DexRoute
  '/lucky': typeof LuckyRoute
  '/shadow': typeof ShadowRoute
  '/shiny': typeof ShinyRoute
  '/unown': typeof UnownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dex' | '/lucky' | '/shadow' | '/shiny' | '/unown'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dex' | '/lucky' | '/shadow' | '/shiny' | '/unown'
  id: '__root__' | '/' | '/dex' | '/lucky' | '/shadow' | '/shiny' | '/unown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DexRoute: typeof DexRoute
  LuckyRoute: typeof LuckyRoute
  ShadowRoute: typeof ShadowRoute
  ShinyRoute: typeof ShinyRoute
  UnownRoute: typeof UnownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unown': {
      id: '/unown'
      path: '/unown'
      fullPath: '/unown'
      preLoaderRoute: typeof UnownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shiny': {
      id: '/shiny'
      path: '/shiny'
      fullPath: '/shiny'
      preLoaderRoute: typeof ShinyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow': {
      id: '/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof ShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucky': {
      id: '/lucky'
      path: '/lucky'
      fullPath: '/lucky'
      preLoaderRoute: typeof LuckyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DexRoute: DexRoute,
  LuckyRoute: LuckyRoute,
  ShadowRoute: ShadowRoute,
  ShinyRoute: ShinyRoute,
  UnownRoute: UnownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
